[package]
name = "rs-xmr-cryp"
version = "0.1.0"
authors = ["TheCharlatan <seb.kung@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.26"
bindgen = "0.45.0"
