[package]
name = "monero-cryp"
version = "0.1.0"
authors = ["TheCharlatan <sbe.kung@gmail.com>"]

build = "src/build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hex = "0.4"
rand = "0.6"
libc = "0.2.45"

[build-dependencies]
cc = "1.0.26"
bindgen = "0.45.0"

